FROM golang:1.12 as builder

RUN mkdir -p /podinfo/
WORKDIR /podinfo

ARG VERSION=unknown
ARG GITCOMMIT=unknown

ADD https://github.com/stefanprodan/podinfo/archive/3.0.0.tar.gz .
RUN tar xzf 3.0.0.tar.gz --strip 1

RUN GOPROXY=https://proxy.golang.org go mod download

RUN go test -v -race ./...

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w \
    -X github.com/stefanprodan/podinfo/pkg/version.REVISION=${GIT_COMMIT}" \
    -a -o bin/podinfo cmd/podinfo/*

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w \
    -X github.com/stefanprodan/podinfo/pkg/version.REVISION=${GIT_COMMIT}" \
    -a -o bin/podcli cmd/podcli/*

FROM alpine:3.10

RUN addgroup -S app \
    && adduser -S -g app app \
    && apk --no-cache add \
    curl openssl netcat-openbsd

WORKDIR /home/app

COPY --from=builder /podinfo/bin/podinfo .
COPY --from=builder /podinfo/bin/podcli /usr/local/bin/podcli
COPY --from=builder /podinfo/ui ./ui
RUN chown -R app:app ./

USER app

CMD ["./podinfo"]
