---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:etrikp/helm-operator-get-started
    path: charts/podinfo-v1
    ref: master
  values:
    ingress:
      enabled: true
      hosts:
        - podinfo-rc
    image:
      repository: nominalintegrations/podinfo
      tag: stg-pcxewybu
    replicaCount: 2
    hpa:
      enabled: false
